# =============================================================================
# AUDIO PROCESSING CONSTANTS
# =============================================================================

# Core audio parameters
SAMPLE_RATE = 22050
HOP_LENGTH = 512
N_FFT = 2048
N_MFCC = 13  # Number of MFCC coefficients
MIN_AUDIO_DURATION = 0.1  # seconds
MAX_AUDIO_DURATION = 30.0  # seconds

# Audio file extensions
AUDIO_EXTENSIONS = {".mp3", ".wav"}

# Audio constants (aliases for backward compatibility)
MFCC_COEFFICIENTS = N_MFCC
DEFAULT_SAMPLE_RATE = SAMPLE_RATE
DEFAULT_SONG_LENGTH = MAX_AUDIO_DURATION
DEFAULT_N_FFT = N_FFT
DEFAULT_HOP_LENGTH = HOP_LENGTH
DEFAULT_SEGMENT_LENGTH = MAX_AUDIO_DURATION
DEFAULT_N_MFCC = N_MFCC

# =============================================================================
# MODEL ARCHITECTURE CONSTANTS
# =============================================================================

# Core model parameters
BATCH_SIZE = 64
LEARNING_RATE = 0.0001
MAX_EPOCHS = 500
WEIGHT_DECAY = 1e-5
OPTIMIZER = "adam"
LOSS_FUNCTION = "crossentropy"
LR_SCHEDULER = True
CLASS_WEIGHT = "auto"
LABEL_SMOOTHING = 0.1
INITIALIZER = "xavier"
NUM_CLASSES = 10

# RNN/LSTM/GRU parameters
HIDDEN_SIZE = 32
NUM_LAYERS = 2
DROPOUT = 0.1

# CNN parameters
CONV_LAYERS = 4
BASE_FILTERS = 32
KERNEL_SIZE = 3
POOL_SIZE = 2
FC_HIDDEN = 128

# Transformer parameters
NUM_HEADS = 4
FF_DIM = 64
TRANSFORMER_MAX_SEQ_LEN = 500

# xLSTM parameters
XLSTM_HIDDEN_SIZE = 64
XLSTM_NUM_LAYERS = 2
XLSTM_DROPOUT = 0.3
XLSTM_NUM_HEADS = 4
XLSTM_CONV_KERNEL_SIZE = 3

# VGG parameters
VGG_NUM_CLASSES = NUM_CLASSES
VGG_PRETRAINED = False
VGG_DROPOUT = DROPOUT

# GAN parameters
GAN_NOISE_DIM = 100
GAN_HIDDEN_DIM = 256
GAN_NUM_LAYERS = 3
GAN_DROPOUT = 0.2
GAN_N_CRITIC = 5
GAN_LAMBDA_GP = 10.0
GAN_LEARNING_RATE = 0.00005

# FC model parameters
FC_INPUT_DIM = 16796
FC_HIDDEN_DIMS = [512, 256, 128]

# =============================================================================
# TRAINING PROCESS CONSTANTS
# =============================================================================

VALIDATION_SPLIT = 0.2
EARLY_STOPPING_PATIENCE = 50
RANDOM_SEED = 42
NUM_WORKERS = 4
PIN_MEMORY = True
SAVE_BEST_MODEL = True
SAVE_CHECKPOINTS = True
EARLY_STOPPING = True
IMPROVEMENT_THRESHOLD = 0.0005
GRADIENT_CLIP_NORM = 1.0

# Data split parameters
TRAIN_SIZE = 0.7
VAL_SIZE = 0.15
TEST_SIZE = 0.15

# =============================================================================
# SYSTEM CONSTANTS
# =============================================================================

# Exit codes
EXIT_SUCCESS = 0
EXIT_FAILURE = 1
EXIT_INTERRUPT = 2
EXIT_FILE_NOT_FOUND = 3
EXIT_EVALUATION_FAILED = 4

# File size constants
BYTES_PER_KB = 1024.0
BYTES_PER_MB = 1024.0 * 1024.0
BYTES_PER_GB = 1024.0 * 1024.0 * 1024.0

# Plot constants
FIGURE_WIDTH = 10
FIGURE_HEIGHT = 6
DPI = 300

# Data processing constants
AUGMENTATION_FACTOR = 2
NOISE_STD = 0.01
FEATURE_CLIP_MIN = -10
FEATURE_CLIP_MAX = 10
EPSILON = 1e-8

# =============================================================================
# DEFAULT CONSTANTS (for configuration)
# =============================================================================

# Training parameters
DEFAULT_BATCH_SIZE = BATCH_SIZE
DEFAULT_LEARNING_RATE = LEARNING_RATE
DEFAULT_MAX_EPOCHS = MAX_EPOCHS
DEFAULT_WEIGHT_DECAY = WEIGHT_DECAY
DEFAULT_OPTIMIZER = OPTIMIZER
DEFAULT_LOSS_FUNCTION = LOSS_FUNCTION
DEFAULT_LR_SCHEDULER = LR_SCHEDULER
DEFAULT_CLASS_WEIGHT = CLASS_WEIGHT
DEFAULT_LABEL_SMOOTHING = LABEL_SMOOTHING
DEFAULT_INITIALIZER = INITIALIZER
DEFAULT_NUM_CLASSES = NUM_CLASSES

# Model architecture
DEFAULT_HIDDEN_SIZE = HIDDEN_SIZE
DEFAULT_NUM_LAYERS = NUM_LAYERS
DEFAULT_DROPOUT = DROPOUT

# CNN parameters
DEFAULT_CONV_LAYERS = CONV_LAYERS
DEFAULT_BASE_FILTERS = BASE_FILTERS
DEFAULT_KERNEL_SIZE = KERNEL_SIZE
DEFAULT_POOL_SIZE = POOL_SIZE
DEFAULT_FC_HIDDEN = FC_HIDDEN

# CNN default constants
DEFAULT_CNN_CONV_LAYERS = CONV_LAYERS
DEFAULT_CNN_BASE_FILTERS = BASE_FILTERS
DEFAULT_CNN_KERNEL_SIZE = KERNEL_SIZE
DEFAULT_CNN_POOL_SIZE = POOL_SIZE
DEFAULT_CNN_FC_HIDDEN = FC_HIDDEN

# Transformer parameters
DEFAULT_NUM_HEADS = NUM_HEADS
DEFAULT_FF_DIM = FF_DIM
DEFAULT_TRANSFORMER_HEADS = NUM_HEADS
DEFAULT_TRANSFORMER_FF_DIM = FF_DIM
DEFAULT_TRANSFORMER_MAX_SEQ_LEN = TRANSFORMER_MAX_SEQ_LEN
DEFAULT_TRANSFORMER_HIDDEN_SIZE = HIDDEN_SIZE
DEFAULT_TRANSFORMER_NUM_LAYERS = NUM_LAYERS

# xLSTM parameters
DEFAULT_XLSTM_HIDDEN_SIZE = XLSTM_HIDDEN_SIZE
DEFAULT_XLSTM_NUM_LAYERS = XLSTM_NUM_LAYERS
DEFAULT_XLSTM_DROPOUT = XLSTM_DROPOUT
DEFAULT_XLSTM_NUM_HEADS = XLSTM_NUM_HEADS
DEFAULT_XLSTM_CONV_KERNEL_SIZE = XLSTM_CONV_KERNEL_SIZE

# VGG parameters
DEFAULT_VGG_NUM_CLASSES = VGG_NUM_CLASSES
DEFAULT_VGG_PRETRAINED = VGG_PRETRAINED
DEFAULT_VGG_DROPOUT = VGG_DROPOUT

# FC model parameters
DEFAULT_FC_INPUT_DIM = FC_INPUT_DIM
DEFAULT_FC_HIDDEN_DIMS = FC_HIDDEN_DIMS
DEFAULT_FC_DROPOUT = DROPOUT

# Training process
DEFAULT_VALIDATION_SPLIT = VALIDATION_SPLIT
DEFAULT_EARLY_STOPPING_PATIENCE = EARLY_STOPPING_PATIENCE
DEFAULT_RANDOM_SEED = RANDOM_SEED
DEFAULT_NUM_WORKERS = NUM_WORKERS
DEFAULT_PIN_MEMORY = PIN_MEMORY
DEFAULT_SAVE_BEST_MODEL = SAVE_BEST_MODEL
DEFAULT_SAVE_CHECKPOINTS = SAVE_CHECKPOINTS
DEFAULT_EARLY_STOPPING = EARLY_STOPPING
DEFAULT_IMPROVEMENT_THRESHOLD = IMPROVEMENT_THRESHOLD
DEFAULT_GRADIENT_CLIP_NORM = GRADIENT_CLIP_NORM

# Data split
DEFAULT_TRAIN_SIZE = TRAIN_SIZE
DEFAULT_VAL_SIZE = VAL_SIZE
DEFAULT_TEST_SIZE = TEST_SIZE

# RNN/LSTM/GRU default constants
DEFAULT_RNN_HIDDEN_SIZE = HIDDEN_SIZE
DEFAULT_RNN_NUM_LAYERS = NUM_LAYERS
DEFAULT_RNN_DROPOUT = DROPOUT

DEFAULT_LSTM_HIDDEN_SIZE = HIDDEN_SIZE
DEFAULT_LSTM_NUM_LAYERS = NUM_LAYERS
DEFAULT_LSTM_DROPOUT = DROPOUT

DEFAULT_GRU_HIDDEN_SIZE = HIDDEN_SIZE
DEFAULT_GRU_NUM_LAYERS = NUM_LAYERS
DEFAULT_GRU_DROPOUT = DROPOUT

# System constants
DEFAULT_CHECKPOINT_INTERVAL = 10
DEFAULT_LOG_INTERVAL = 100
DEFAULT_DEVICE = "auto"

# Plot constants
DEFAULT_FIGURE_WIDTH = FIGURE_WIDTH
DEFAULT_FIGURE_HEIGHT = FIGURE_HEIGHT
DEFAULT_DPI = DPI

# Data processing
DEFAULT_AUGMENTATION_FACTOR = AUGMENTATION_FACTOR
DEFAULT_NOISE_STD = NOISE_STD
DEFAULT_FEATURE_CLIP_MIN = FEATURE_CLIP_MIN
DEFAULT_FEATURE_CLIP_MAX = FEATURE_CLIP_MAX
DEFAULT_EPSILON = EPSILON
