"""
Constants used throughout GenreDiscern.
"""

# Audio processing constants
SAMPLE_RATE = 22050
HOP_LENGTH = 512
N_FFT = 2048
DEFAULT_N_MFCC = 13  # Default number of MFCC coefficients
MIN_AUDIO_DURATION = 0.1  # Minimum audio duration in seconds
MAX_AUDIO_DURATION = 30.0  # Maximum audio duration in seconds

# Legacy audio constants (for backward compatibility)
MFCC_COEFFICIENTS = 13  # Number of MFCC coefficients (legacy, use DEFAULT_N_MFCC)
DEFAULT_SAMPLE_RATE = 22050
DEFAULT_SONG_LENGTH = 30  # seconds
DEFAULT_N_FFT = 2048
DEFAULT_HOP_LENGTH = 512
DEFAULT_SEGMENT_LENGTH = 30

# Model Constants
DEFAULT_NUM_CLASSES = 10  # Default number of output classes
DEFAULT_BATCH_SIZE = 64
DEFAULT_HIDDEN_SIZE = 32
DEFAULT_NUM_LAYERS = 1
DEFAULT_DROPOUT = 0.1
DEFAULT_LEARNING_RATE = 0.01
DEFAULT_MAX_EPOCHS = 500
DEFAULT_EARLY_STOPPING_PATIENCE = 10
DEFAULT_WEIGHT_DECAY = 1e-5
DEFAULT_OPTIMIZER = "adam"
DEFAULT_LOSS_FUNCTION = "crossentropy"
DEFAULT_LR_SCHEDULER = True

# Training Constants
DEFAULT_VALIDATION_SPLIT = 0.2
DEFAULT_RANDOM_SEED = 42
DEFAULT_NUM_WORKERS = 4
DEFAULT_CHECKPOINT_INTERVAL = 10
DEFAULT_LOG_INTERVAL = 100
DEFAULT_PATIENCE = 15
DEFAULT_DEVICE = "auto"
DEFAULT_PIN_MEMORY = True
DEFAULT_SAVE_BEST_MODEL = True
DEFAULT_SAVE_CHECKPOINTS = True
DEFAULT_EARLY_STOPPING = True

# Data Split Constants
DEFAULT_TRAIN_SIZE = 0.7
DEFAULT_VAL_SIZE = 0.15
DEFAULT_TEST_SIZE = 0.15

# Audio File Extensions
AUDIO_EXTENSIONS = {".mp3", ".wav", ".flac", ".m4a", ".ogg", ".aac"}

# CNN Architecture Defaults
DEFAULT_CNN_CONV_LAYERS = 4
DEFAULT_CNN_BASE_FILTERS = 32
DEFAULT_CNN_KERNEL_SIZE = 3
DEFAULT_CNN_POOL_SIZE = 2
DEFAULT_CNN_FC_HIDDEN = 128

# Plot Constants
DEFAULT_FIGURE_WIDTH = 10
DEFAULT_FIGURE_HEIGHT = 6
DEFAULT_DPI = 300

# File Size Constants
BYTES_PER_KB = 1024.0
BYTES_PER_MB = 1024.0 * 1024.0
BYTES_PER_GB = 1024.0 * 1024.0 * 1024.0

# Exit Codes
EXIT_SUCCESS = 0
EXIT_FAILURE = 1
EXIT_INTERRUPT = 2
EXIT_FILE_NOT_FOUND = 3
EXIT_EVALUATION_FAILED = 4

# GTZAN Genre Names
GTZAN_GENRES = [
    "blues",
    "classical",
    "country",
    "disco",
    "hiphop",
    "jazz",
    "metal",
    "pop",
    "reggae",
    "rock",
]

# === UNIFIED MODEL ARCHITECTURE CONSTANTS ===
# Single source of truth for all model parameter defaults

# === CORE TRAINING PARAMETERS ===
DEFAULT_BATCH_SIZE = 32
DEFAULT_LEARNING_RATE = 0.00001
DEFAULT_MAX_EPOCHS = 500
DEFAULT_WEIGHT_DECAY = 1e-4
DEFAULT_OPTIMIZER = "adamw"
DEFAULT_LOSS_FUNCTION = "crossentropy"
DEFAULT_LR_SCHEDULER = True
DEFAULT_CLASS_WEIGHT = "auto"

# === MODEL ARCHITECTURE PARAMETERS ===
# RNN/LSTM/GRU parameters (unified)
DEFAULT_HIDDEN_SIZE = 64  # Single value for all RNN variants
DEFAULT_NUM_LAYERS = 2
DEFAULT_DROPOUT = 0.3

# CNN parameters
DEFAULT_CONV_LAYERS = 4
DEFAULT_BASE_FILTERS = 32
DEFAULT_KERNEL_SIZE = 3
DEFAULT_POOL_SIZE = 2
DEFAULT_FC_HIDDEN = 128

# CNN legacy constants (for backward compatibility)
DEFAULT_CNN_CONV_LAYERS = DEFAULT_CONV_LAYERS
DEFAULT_CNN_BASE_FILTERS = DEFAULT_BASE_FILTERS
DEFAULT_CNN_KERNEL_SIZE = DEFAULT_KERNEL_SIZE
DEFAULT_CNN_POOL_SIZE = DEFAULT_POOL_SIZE
DEFAULT_CNN_FC_HIDDEN = DEFAULT_FC_HIDDEN

# Transformer parameters
DEFAULT_NUM_HEADS = 4
DEFAULT_FF_DIM = 64

# xLSTM parameters
DEFAULT_XLSTM_HIDDEN_SIZE = 64
DEFAULT_XLSTM_NUM_LAYERS = 2
DEFAULT_XLSTM_DROPOUT = 0.3
DEFAULT_XLSTM_NUM_HEADS = 4
DEFAULT_XLSTM_CONV_KERNEL_SIZE = 3

# VGG parameters
DEFAULT_VGG_NUM_CLASSES = 10
DEFAULT_VGG_PRETRAINED = True
DEFAULT_VGG_DROPOUT = 0.3

# FC model parameters
DEFAULT_FC_INPUT_DIM = 16796  # Default fallback for flattened MFCC
DEFAULT_FC_HIDDEN_DIMS = [512, 256, 128]

# Transformer parameters (additional)
DEFAULT_TRANSFORMER_MAX_SEQ_LEN = 500

# === TRAINING PROCESS PARAMETERS ===
DEFAULT_VALIDATION_SPLIT = 0.2
DEFAULT_EARLY_STOPPING_PATIENCE = 25
DEFAULT_RANDOM_SEED = 42
DEFAULT_NUM_WORKERS = 4
DEFAULT_PIN_MEMORY = True
DEFAULT_SAVE_BEST_MODEL = True
DEFAULT_SAVE_CHECKPOINTS = True
DEFAULT_EARLY_STOPPING = True
DEFAULT_IMPROVEMENT_THRESHOLD = 0.0005
DEFAULT_GRADIENT_CLIP_NORM = 1.0

# === DATA SPLIT PARAMETERS ===
DEFAULT_TRAIN_SIZE = 0.7
DEFAULT_VAL_SIZE = 0.15
DEFAULT_TEST_SIZE = 0.15

# === LEGACY CONSTANTS (for backward compatibility) ===
# These are kept for compatibility but should use the unified constants above
DEFAULT_FC_DROPOUT = DEFAULT_DROPOUT
DEFAULT_CNN_DROPOUT = 0.2
DEFAULT_TRANSFORMER_HEADS = DEFAULT_NUM_HEADS
DEFAULT_TRANSFORMER_FF_DIM = DEFAULT_FF_DIM
DEFAULT_XLSTM_DROPOUT = DEFAULT_XLSTM_DROPOUT

# RNN/LSTM/GRU Defaults (legacy - use unified constants)
DEFAULT_RNN_HIDDEN_SIZE = DEFAULT_HIDDEN_SIZE
DEFAULT_RNN_NUM_LAYERS = DEFAULT_NUM_LAYERS
DEFAULT_RNN_DROPOUT = DEFAULT_DROPOUT

DEFAULT_LSTM_HIDDEN_SIZE = DEFAULT_HIDDEN_SIZE
DEFAULT_LSTM_NUM_LAYERS = DEFAULT_NUM_LAYERS
DEFAULT_LSTM_DROPOUT = DEFAULT_DROPOUT

DEFAULT_GRU_HIDDEN_SIZE = DEFAULT_HIDDEN_SIZE
DEFAULT_GRU_NUM_LAYERS = DEFAULT_NUM_LAYERS
DEFAULT_GRU_DROPOUT = DEFAULT_DROPOUT

# xLSTM Defaults (legacy)
DEFAULT_XLSTM_HIDDEN_SIZE = DEFAULT_XLSTM_HIDDEN_SIZE
DEFAULT_XLSTM_NUM_LAYERS = DEFAULT_XLSTM_NUM_LAYERS

# Transformer additional defaults (legacy)
DEFAULT_TRANSFORMER_HIDDEN_SIZE = DEFAULT_HIDDEN_SIZE
DEFAULT_TRANSFORMER_NUM_LAYERS = DEFAULT_NUM_LAYERS

# Data Processing Constants
DEFAULT_AUGMENTATION_FACTOR = 2
DEFAULT_NOISE_STD = 0.01
DEFAULT_FEATURE_CLIP_MIN = -10
DEFAULT_FEATURE_CLIP_MAX = 10
DEFAULT_EPSILON = 1e-8

# UI Constants (for any remaining GUI elements)
DEFAULT_WINDOW_WIDTH = 600
DEFAULT_WINDOW_HEIGHT = 400
DEFAULT_WINDOW_X = 100
DEFAULT_WINDOW_Y = 100
DEFAULT_BUTTON_WIDTH = 100
DEFAULT_BUTTON_HEIGHT = 30
